name=NTP
version=1.8.0
author=Stefan Staub
maintainer=Stefan Staub <https://github.com/sstaub>
sentence=NTP library
paragraph=NTP library for Arduino framework, using standard time.h library.
category=Timing
url=https://github.com/sstaub/NTP
architectures=*
includes=NTP.h